Calendar and sequence functionality
7theta/tempus pull request #6
Opened 2022-08-03 20:16 UTC by natasha-sandhu

2022-08-03 20:25 UTC, tom7t commented on src/tempus/calendar.cljc
> +            (= week-start :monday) inc)]
Looks like `x` is only used in the `:week` case. Don't need to let bind it here.

2022-08-03 20:26 UTC, tom7t commented on src/tempus/calendar.cljc
> +            (= week-start :monday) dec)]
Same comment as below.

2022-08-03 20:27 UTC, tom7t commented on src/tempus/calendar.cljc
> +        year-2 (t/year ts2)]
Not sure let-binding everything is necessary. Each function would only get called once in each case, but by let binding them you're actually computing all possible values even if you might only need a subset of them.

2022-08-03 20:29 UTC, tom7t commented on src/tempus/calendar.cljc
> +        year-2 (t/year ts2)]
e.g. the `:month` case could just be
```
(and (= (t/month ts2) (t/month ts1))
     (= (t/year ts2) (t/year ts1)))
```

2022-08-03 20:32 UTC, tom7t commented on src/tempus/calendar.cljc
> +        year (t/year ts)
Same comment as above for this function and for the `end` function about let binding. I think you can just inline all of your `(t/... )` function calls as they will only be called at most one time per case, so pre-computing them doesn't save you anything (and costs you extra computation, as you don't need all of them in all cases).

2022-08-04 12:47 UTC, tom7t approved these changes
Looks good

2022-08-05 15:07 UTC, joel7t commented on src/tempus/calendar.cljc
> +  [type ts1 ts2]
Using `type` as the input parameter seems ambiguous to me.  It shadows `clojure.core/type`, and it leaves me wondering if the function expects a class as input.  Could we use `time-unit` instead of `type`?  Or something else is fine too.  What input parameter name would give a future user the best clue about what value to provide for the first input?

The shadowing is not a big deal as we do it in other places, but I always want to point it out to raise awareness.

The same comment applies to other functions in this PR.

2022-08-09 12:17 UTC, joel7t requested changes

2022-08-09 12:17 UTC, joel7t commented on src/tempus/core.clj
> +      weekday)))
The `if` isn't needed anymore.  `mod` will return a number from 0 to 6.

The output of this function is currently always 0.

2022-08-09 15:47 UTC, natasha-sandhu commented on src/tempus/interval.cljc
> +(defn seq
Renamed to `seq-of`

2022-08-09 19:48 UTC, joel7t approved these changes

2022-08-10 19:21 UTC, sandhu requested changes

2022-08-10 19:21 UTC, sandhu commented on src/tempus/core.clj
> +(defn day-of-year
Should be removed

2022-08-10 19:21 UTC, sandhu commented on src/tempus/core.cljs
> +    (j/call date-time :toIsoString false true))
The printed value should print the same way in clj and cljs

2022-08-10 19:21 UTC, sandhu commented on src/tempus/core.cljs
> +        (j/call :toIsoString false true)
See above re format

2022-08-10 19:55 UTC, sandhu approved these changes

2022-08-10 19:55 UTC, merged